### ISSUE TITLE
first round edits with greg 

### ISSUE THREAD

**Issue by gwenchee** [arfc/2018-chee-predicting-ans#1]
This issue can be closed after Greg reviews https://github.com/gwenchee/2018-chee-predicting-ans/tree/draft1 and I PR with the changes that he added.

**Comment by gtw2** [comment]
There was a fair bit of passive voice I tried to correct as well as some word choice. Only major change I could see was possibly adding a Background: Cyclus to clear up some terminology used later (particularly archetype). If my handwriting or suggestions are unclear feel free to clarify: [round1.pdf](https://github.com/arfc/2018-chee-predicting-ans/files/2087226/chee-predicting-ans_annotated.pdf).

**Comment by gwenchee** [comment]
Done!
