### ISSUE TITLE
bae reveiw

### ISSUE THREAD

**Issue by jbae11** [arfc/2018-chee-predicting-ans#7]
Great! Looks good, it'd be nice to maybe have some plots of the UDB burnup distribution, but I know that your brilliance is limited by the 4-page limit :)
 Let me know if you have any questions about my comments
[chee-predicting-ans_annotate.pdf](https://github.com/arfc/2018-chee-predicting-ans/files/2299161/chee-predicting-ans_annotate.pdf)

**Comment by gwenchee** [comment]
Thanks! I have merged your comments into my final document 👍
